# Extra ingress test

image:
  repository: jwilder/whoami
  tag: latest

ingress:
  enabled: true
  port: 8000
  domains: ['example.com']
  class: nginx
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: dummy-config;
  extra:
    additional-annotation:
      domains: ['custom-annotation.example.com']
      annotations:
        key: value
    other-port:
      port: 1337
      domains: ['custom-port.example.com']
      annotations:
        nginx.ingress.kubernetes.io/configuration-snippet: other-dummy-config;
      protocol: grpc
      timeoutSeconds: 5
    extra-port:
      portRef: other-port
      domains: ['custom-port.example.com']
      annotations:
        nginx.ingress.kubernetes.io/server-snippet: other-dummy-config;
      protocol: grpc
      timeoutSeconds: 5
